version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: php:7.3-apache
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git

      - checkout

      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"

      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install project dependencies
          command: php composer.phar install --prefer-dist

      # Re-cache dependencies
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:

      - run:
          name: Run Unit tests
          command: vendor/bin/phpunit
